#!/usr/bin/env python3
"""World summary — generates WORLD.md (an accurate atlas) and flags structural gaps.

Reads the live data and writes docs/../WORLD.md so the overview can never drift from
the actual content. Also prints a short gap report (regions missing a landmark, a
Crossroads, a champion, or an encounter table). Run after any content change:

    python3 tools/world_summary.py            # writes WORLD.md, prints gaps
    python3 tools/world_summary.py --check     # gaps only, non-zero exit if any
"""
from __future__ import annotations

import glob
import json
import os
import sys
from collections import Counter

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
DATA = os.path.join(ROOT, "data")
TYPES = ["normal", "fire", "water", "grass", "electric", "earth", "wind", "mystic"]


def load(p):
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def main() -> int:
    check_only = "--check" in sys.argv
    maps = {}
    for f in glob.glob(os.path.join(DATA, "regions", "maps", "*.json")):
        m = load(f)
        maps[m["id"]] = m
    regions = sorted((load(f) for f in glob.glob(os.path.join(DATA, "regions", "region_*.json"))),
                     key=lambda r: r["order"])
    creatures = load(os.path.join(DATA, "creatures", "creatures.json"))["creatures"]
    trainers = {t["id"]: t for t in load(os.path.join(DATA, "trainers", "trainers.json"))["trainers"]}
    quests = load(os.path.join(DATA, "quests", "quests.json"))["quests"]
    endings = load(os.path.join(DATA, "endings", "endings.json"))["endings"]
    dialogs = []
    for df in glob.glob(os.path.join(DATA, "dialogs", "*.json")):
        dialogs += load(df).get("dialogs", [])

    species_per = Counter(c.get("origin_region", "?") for c in creatures)
    maps_per = Counter(m.get("region", "?") for m in maps.values())

    # landmark display names from the map files
    def landmark_name(rid):
        return maps.get(f"{rid}_landmark", {}).get("display_name", "—")

    def champion(rid):
        for cid in (f"{rid}_champion", f"{rid}_sovereign", f"{rid}_marshal",
                    "verdantia_sovereign", "aquilon_marshal"):
            if cid in trainers and trainers[cid].get("boss"):
                # region-scoped only
                pass
        # prefer a boss trainer whose id starts with the region and grants the crest
        for tid, t in trainers.items():
            if tid.startswith(rid) and t.get("reward_badge") == f"{rid}_crest":
                return t["display_name"]
        return {"verdantia": "Sovereign Laurel", "aquilon": "Marshal Eirwen"}.get(rid, "—")

    # --- gap report ---
    gaps = []
    for r in regions:
        rid = r["id"]
        if f"{rid}_crossroads" not in maps:
            gaps.append(f"{rid}: no Crossroads map")
        if f"{rid}_landmark" not in maps:
            gaps.append(f"{rid}: no landmark map")
        for t in TYPES:
            if f"{rid}_gym_{t}" not in maps:
                gaps.append(f"{rid}: missing {t} gym")
        et = r.get("regional_rules", {}).get("encounter_table", "")
        if not et:
            gaps.append(f"{rid}: no encounter table in manifest")

    if check_only:
        if gaps:
            print(f"✗ {len(gaps)} structural gap(s):")
            for g in gaps:
                print("  -", g)
            return 1
        print("✓ No structural gaps: every region has a Crossroads, 8 gyms and a landmark.")
        return 0

    # --- write WORLD.md ---
    lines = []
    lines.append("# WORLD.md — Atlas\n")
    lines.append("> Auto-generated by `python3 tools/world_summary.py` from the live data — "
                 "do not edit by hand. All content is original (see `LICENSE_NOTES.md`).\n")
    lines.append(f"**{len(regions)} regions · {len(maps)} maps · {len(creatures)} creatures · "
                 f"{len(trainers)} trainers · {len(quests)} quests · {len(dialogs)} dialogs · "
                 f"{len(endings)} endings**\n")
    lines.append("## Regions, in order\n")
    lines.append("Each region: a gate/entry, wilds, a **Crossroads** hub with **8 type-themed "
                 "gyms**, a **League** (four Elites in sequence → Champion → crest), a unique "
                 "**landmark**, and Battle Courts for grinding. Regions chain by flag-gated ports "
                 "with free return trips.\n")
    lines.append("| # | Region | Rec. levels | Champion | Landmark | Maps | Native species |")
    lines.append("|---|--------|-------------|----------|----------|------|----------------|")
    for r in regions:
        rid = r["id"]
        lo = r.get("recommended_level_min", "?")
        hi = r.get("recommended_level_max", "?")
        lines.append(f"| {r['order']} | **{r['display_name']}** | {lo}–{hi} | {champion(rid)} "
                     f"| {landmark_name(rid)} | {maps_per.get(rid, 0)} | {species_per.get(rid, 0)} |")

    lines.append("\n## Progression spine\n")
    order_names = " → ".join(r["display_name"] for r in regions)
    lines.append(f"{order_names}\n")
    lines.append("Within a region: enter → clear the wilds scout → reach the Crossroads → beat the "
                 "8 gyms (any order) → the gym-circuit quest opens the League → beat the four Elites "
                 "in sequence → beat the Champion for the crest → the northern port opens to the next "
                 "region. You keep your team, box, Pokédex and items across every region.\n")

    lines.append("## Story landmarks\n")
    lines.append("| Region | Landmark | What it is |")
    lines.append("|--------|----------|------------|")
    blurbs = {
        "verdantia": "The first bond between human and creature.",
        "aquilon": "A lighthouse kept lit by a creature that never sleeps.",
        "cindral": "The mountain's heartbeat, felt underfoot.",
        "solane": "The real oasis beside the false one.",
        "umbra": "Where day and night converse — and Lieutenant Mourn waits.",
        "ferrock": "Where creatures forged a region, hammer by hammer.",
        "brume": "A town the fen rose to keep.",
        "lumen": "Crystals that hold the valley's memories.",
        "zephyra": "Where a sky-spirit alights once a generation.",
    }
    for r in regions:
        rid = r["id"]
        lines.append(f"| {r['display_name']} | {landmark_name(rid)} | {blurbs.get(rid, '')} |")

    lines.append("\n## The Hollow Order arc\n")
    lines.append("Defector **Sable** (Cindral) → agents **Vole** (Cindral), **Cinder** (Ferrock), "
                 "**Wisp** (Lumen) → **Lieutenant Mourn** (Duskbell Grove, Umbra) → the **Archon** "
                 "(Zephyra wilds) → a **mercy / justice** choice that, with your rival relationship, "
                 "selects one of 8 endings. See `STORY.md`.\n")

    lines.append("## Endings\n")
    for e in endings:
        lines.append(f"- **{e['title']}**")
    lines.append("")

    out = os.path.join(ROOT, "WORLD.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out} ({len(regions)} regions, {len(maps)} maps).")
    if gaps:
        print(f"⚠ {len(gaps)} structural gap(s):")
        for g in gaps:
            print("  -", g)
    else:
        print("✓ No structural gaps.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
